sudo: required
services:
  - docker

before_install:
  - docker build -t moni-github/react-test -f ./client/Dockerfile.dev ./client

script:
  -  docker run -e CI=true moni-github/react-test npm test -- --coverage
  
after_success:
  - docker build -t moni-github/multi-client ./client
  - docker build -t moni-github/multi-nginx ./nginx
  - docker build -t moni-github/multi-server ./server
  - docker build -t moni-github/multi-worker ./worker
  
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  -docker push moni-github/multi-client
  -docker push moni-github/multi-nginx
  -docker push moni-github/multi-server
  -docker push moni-github/multi-worker